services:
  cloudflared:
    image: cloudflare/cloudflared:2025.2.0
    container_name: cloudflared_tunnel
    restart: always
    env_file: ../../.env
    command: tunnel --no-autoupdate run --token eyJhIjoiMDg2NDMwMjQ4Y2RhNWYwYmE5ZWVjMjRmZTc4YjBhMTAiLCJ0IjoiZDFiY2U5ODktNzRhNi00MzhlLWIzNTItZTM3MTk1ZDI2YjYyIiwicyI6Ik5qUmtaRE5tT1dVdE5XTTNZUzAwWkdWbExXRXdOemt0TTJaa1lqaG1NelEwTnpsaSJ9
    networks:
      - secure-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  secure-net:
    external: true
